name: EIB Request Form
description: Mass data changes via EIB uploads.
title: "[EIB]: "
body:
  - type: markdown
    attributes:
      value: |+
        This form is for mass data changes via EIB uploads.
        <br />
  - type: input
    id: Requester
    attributes:
      label: Requester
      description: Who requested this change?
      placeholder: Finance..
    validations:
      required: true
