name: EIB Request Form
description: Mass data changes via EIB uploads.
title: "[EIB]: "
body:
  - type: markdown
    attributes:
      value: |+
        This form is for mass data changes via EIB uploads.
        <br />
  - type: input
    id: Requester
    attributes:
      label: Requester
      description: Who requested this change?
      placeholder: Finance..
    validations:
      required: true
  - type: textarea
    id: TLDR
    attributes:
      label: TLDR
      description: What is the TLDR of this change?
      placeholder: Insert text here...
    validations:
      required: true
  - type: input
    id: Deadline
    attributes:
      label: Deadline
      description: What is the deadline for this request?
      placeholder: Insert text/date here...
    validations:
      required: true
  - type: dropdown
    id: Template
    attributes:
      label: Template
      description: Which EIB template are you using?
      options:
        - "Change Org Assignment"
        - "Request Compensation Change"
        - "Add Stock Grant"
        - "Change Job"
        - "Hire"
        - "Edit Position"
        - "Other"
    validations:
      required: true
  - type: input
    id: Volume
    attributes:
      label: Volume
      description: How many changes are you making in one upload?
      placeholder: eg.1200
    validations:
      required: true
