name: EIB Request Form
description: Mass data changes via EIB uploads.
title: "[EIB]: "
body:
  - type: markdown
    attributes:
      value: |+
        This form is for mass data changes via EIB uploads.
        <br />
  - type: input
    id: Requester
    attributes:
      label: Requester
      description: Who requested this change?
      placeholder: Finance..
    validations:
      required: true
  - type: textarea
    id: TLDR
    attributes:
      label: TLDR
      description: What is the TLDR of this change?
      placeholder: Insert text here...
    validations:
      required: true
  - type: input
    id: Deadline
    attributes:
      label: Deadline
      description: What is the deadline for this request?
      placeholder: Insert text/date here...
    validations:
      required: true
  - type: dropdown
    id: Template
    attributes:
      label: Template
      description: Which EIB template are you using?
      options:
        - "Change Org Assignment"
        - "Request Compensation Change"
        - "Add Stock Grant"
        - "Change Job"
        - "Hire"
        - "Edit Position"
        - "Other"
    validations:
      required: true
  - type: input
    id: Volume
    attributes:
      label: Volume
      description: How many changes are you making in one upload?
      placeholder: eg.1200
    validations:
      required: true
  - type: checkboxes
    id: Inform_Others
    attributes:
      label: Relevant Party
      description: Please notify all teams who will be affected by this change prior to making any changes in production
      options:
        - label: IT team (@Shopify/okta-team)
        - label: Vault team (@Shopify/vault-tools)
        - label: People Analytics (@Shopify/people-analytics)
        - label: (@Shopify/it-device-identity)
        - label: Compensation Team
        - label: Finance Team
    validations:
      required: true
  - type: textarea
    id: Inform_Others_2
    attributes:
      label: Relevant Party (Alternative way)
      description: Another way to inform all parties:IT team (@Shopify/okta-team); Vault team (@Shopify/vault-tools), People Analytics (@Shopify/people-analytics),  (@Shopify/it-device-identity)
      placeholder: Please copy paste the relevant party from abover here
    validations:
      required: true
